#!/usr/bin/python

import sys
import os
import pwd
from commands import getstatusoutput

sys.dont_write_bytecode = True

from gui_gtk import *

def install(self):
    gtk.main()

class autostart:
    def __init__(self):
        pass

    def add_autostart(self):
        autostart_desktop="""
[Desktop Entry]
Type=Application
Name = Magick Rotation for tablet pc's
Exec = %s
Icon = redo
Comment=Helps with automatic rotation
"""
        autostart_file_path = "~/.config/autostart/magick-rotation.desktop"

        if os.path.exists("/usr/share/magick-rotation/magick-rotation"):
            usr_share = "/usr/share/magick-rotation/magick-rotation"
            if not os.path.isdir(os.path.expanduser('~')+"/.config/autostart/"):
                os.mkdir(os.path.expanduser('~')+"/.config/autostart/")
            wr=open(os.path.expanduser(autostart_file_path), "w")
            wr.write(autostart_desktop % usr_share)
            wr.close()

if __name__ == "__main__":
    path = "."
    if sys.argv:
        path = os.path.dirname(sys.argv[0])
        if not path:
            path = "."

    command = "stat /usr/bin/gksudo"
    is_gksudo = getstatusoutput(command) [0]
    if is_gksudo == 0:
       sudo = "gksudo "
       
    command = "stat /usr/bin/gksu"
    is_gksu = getstatusoutput(command) [0]
    if is_gksu == 0:
       sudo = "gksu "

    command = "stat /usr/bin/kdesudo"
    is_kdesudo = getstatusoutput(command)[0]
    if is_kdesudo == 0:
        sudo = "kdesudo -c "

    # for Fedora
    command = "stat /usr/bin/beesu"
    is_beesu = getstatusoutput(command) [0]
    if is_beesu == 0:
        sudo = "beesu "

    # for openSUSE
    command = "stat /usr/bin/kdesu"
    is_kdesu = getstatusoutput(command)[0]
    if is_kdesu == 0:
        sudo = "kdesu -c "

    wl = path + "/whitelist.py"
    val = getstatusoutput(wl)[0]
    
    usr_for_group = pwd.getpwuid(os.getuid()).pw_name
    # pass username as a command line argument
    command = sudo + "'python " + path + "/installer_gtk.py " + \
              usr_for_group + "'"
    success = getstatusoutput(command)[0]
    start = autostart()
    start.add_autostart()
    sys.exit(success)

    magick_install = install()
    magick_install.run()

##############################################################
##  This program is free software; you can redistribute it  ##
##  and/or modify it under the terms of the GNU General     ##
##  Public license as published by the Free Software        ##
##  Foundation; either version 2 of the License, or (at     ## 
##  your option) any later version.                         ##
##############################################################
