#!/usr/bin/python

import sys
import os
import pwd
from commands import getstatusoutput

def uninstall(self):
    gtk.main()

if __name__ == "__main__":
    path = "."
    if sys.argv:
        path = os.path.dirname(sys.argv[0])
        if not path:
            path = "."

    command = "stat /usr/bin/gksudo"
    is_gksudo = getstatusoutput(command) [0]
    if is_gksudo == 0:
       sudo = "gksudo "
       
    command = "stat /usr/bin/gksu"
    is_gksu = getstatusoutput(command) [0]
    if is_gksu == 0:
       sudo = "gksu "

    command = "stat /usr/bin/kdesudo"
    is_kdesudo = getstatusoutput(command)[0]
    if is_kdesudo == 0:
        sudo = "kdesudo -c "

    # for Fedora
    command = "stat /usr/bin/beesu"
    is_beesu = getstatusoutput(command) [0]
    if is_beesu == 0:
        sudo = "beesu "

    # for openSUSE
    command = "stat /usr/bin/kdesu"
    is_kdesu = getstatusoutput(command)[0]
    if is_kdesu == 0:
        sudo = "kdesu -c "

    # use gsettings to remove Magick icon from Unity tray whitelist
    # or disable Magick extension in Gnome Shell
    gset = path + "/gset_rmkeyval.py"
    val = getstatusoutput(gset)[0]

    usr_for_group = pwd.getpwuid(os.getuid()).pw_name
    # pass username as a command line argument
    command = sudo + "'python " + path + "/uninstaller_gtk.py " + \
              usr_for_group + "'"
    success = getstatusoutput(command)[0]
    sys.exit(success)

    magick_uninstall = uninstall()
    magick_uninstall.run()

##############################################################
##  This program is free software; you can redistribute it  ##
##  and/or modify it under the terms of the GNU General     ##
##  Public license as published by the Free Software        ##
##  Foundation; either version 2 of the License, or (at     ## 
##  your option) any later version.                         ##
##############################################################
